In [16]:
#Section-A
#1
num = [23,45,2,6,13]#list declaration
num.append(59)#append operation will add the number at the end of the list
print(num)#display list
num.extend([56,99])#extend operation will add multiple elements to given data structure at the end
print(num)
num.insert(3,7)#insert operation will add element at the given index of the data structure
print(num)
num.remove(45)#remove operation will delete the matching element given from the data structure
print(num)
num.pop(2)# pop operation will delete the element of provided index from the data structure
print(num)
print(num.index(13))#index operation will give the index of the element provided from the data structure
print(num.count(99))#count operation will give number of times provided element has occured in that data structure
num.sort()#sort operation will sort the data structure in ascending order by default
print(num)
num.reverse()#reverse opeartion will reverse the data structure
print(num)
num.clear()#clear operation will delete all the elements from the data structure
print(num)

[23, 45, 2, 6, 13, 59]
[23, 45, 2, 6, 13, 59, 56, 99]
[23, 45, 2, 7, 6, 13, 59, 56, 99]
[23, 2, 7, 6, 13, 59, 56, 99]
[23, 2, 6, 13, 59, 56, 99]
3
1
[2, 6, 13, 23, 56, 59, 99]
[99, 59, 56, 23, 13, 6, 2]
[]


In [21]:
#2
name = ("Nehal","Danny","Pooja")
print(name)
name[2] = "Mark" #tuples are immutable.Hence after declaration if we try to modify it then it throws error.
print(name)

('Nehal', 'Danny', 'Pooja')


TypeError: 'tuple' object does not support item assignment

In [24]:
#3
numbers = {2,3,4,2,5,3,6,3,7,8,3,8}
"""set data structure does not allow duplicate values.Hence even if we provided duplicates during declaration, the set
eliminate those."""
print(numbers)

{2, 3, 4, 5, 6, 7, 8}


In [31]:
#4
info = {"name" : "Nehal" , "age" : 23 , "city" : "Pune"}#dictionary declaration
print(info)
info["age"] = 22 #modifying exsisting value to new value
print(info)
info["email"] = "nk@gmail.com" #adding new key and value.It is mandatory to add value when declaring key.
print(info)

{'name': 'Nehal', 'age': 23, 'city': 'Pune'}
{'name': 'Nehal', 'age': 22, 'city': 'Pune'}
{'name': 'Nehal', 'age': 22, 'city': 'Pune', 'email': 'nk@gmail.com'}


In [2]:
#5
age = int(input("Enter your age: "))#user input
if age >= 18: #conditional statement
    print("You are eligible to vote!")
else:
    print("You are not eligible to vote")

Enter your age:  23


You are eligible to vote!


In [10]:
#6
marks = int(input("Enter your marks: "))
if marks >= 90 and marks <101:
    print("Grade A")
elif marks >= 75 and marks <90:
    print("Grade B")
elif marks >= 50 and marks < 75:
    print("Grade C")
elif marks >= 0 and marks < 50:
    print("Fail")
elif marks > 100:
    print("Please enter appropriate marks")

    

Enter your marks:  82


Grade B


In [14]:
#7
num = int(input("Enter a number: "))
if num > 0:
    if num % 2 == 0:
        print("Positive and even number entered")
    else:
        print("Positive and odd number entered")
elif num == 0:
    print("Zero is entered")
elif num < 0:
    print("Negative number entered")

Enter a number:  -4


Negative number entered


In [19]:
#Section-B
#1
import numpy as np
arr = np.array(5)
print(arr)
oneD_arr = np.array([1,2,3,4,5])
print(oneD_arr)
twoD_arr = np.array([[10,20,30],[40,50,60]])
print(twoD_arr)

5
[1 2 3 4 5]
[[10 20 30]
 [40 50 60]]


In [45]:
#2
array1 = np.random.randint(0,101,size=(4,4))
print(array1)

[[ 91  52  83  80]
 [100  21  85  21]
 [ 77  29  42   5]
 [ 34  41  16  92]]


In [46]:
#3
import pandas as pd
new_arr = np.array([[1,2,3],[6,7,8],[4,5,9]])
df = pd.DataFrame(new_arr,columns=['A','B','C'])
print(df)

   A  B  C
0  1  2  3
1  6  7  8
2  4  5  9


In [64]:
#Section-C
#11
details = {
    "Name" : ["Nehal","Aisha","Mark","Elena","Pooja","Harry","Josh","Kevin","Shubham","Maya"],
    "Age" : [23,34,22,25,67,27,19,20,36,45],
    "City" : ["Pune","Mumbai","Delhi","Chennai","Banglore","Hyderabad","Surat","Jaipur","Kolkata","Akola"],
    "Salary" : [12000,20000,30000,40000,50000,6000,73000,29000,20004,12947]
}
new_df = pd.DataFrame(details)
print(new_df)
new_df.info()
new_df.describe()
print(new_df[['Name','City']])
drop_df = new_df.drop('City',axis=1)
print(drop_df)
new_df.at[4,"Salary"] = np.nan
new_df.at[8,"Salary"] = np.nan
print(new_df)
df_na = new_df.fillna(new_df["Salary"].mean())
print(df_na)

      Name  Age       City  Salary
0    Nehal   23       Pune   12000
1    Aisha   34     Mumbai   20000
2     Mark   22      Delhi   30000
3    Elena   25    Chennai   40000
4    Pooja   67   Banglore   50000
5    Harry   27  Hyderabad    6000
6     Josh   19      Surat   73000
7    Kevin   20     Jaipur   29000
8  Shubham   36    Kolkata   20004
9     Maya   45      Akola   12947
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    10 non-null     object
 1   Age     10 non-null     int64 
 2   City    10 non-null     object
 3   Salary  10 non-null     int64 
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes
      Name       City
0    Nehal       Pune
1    Aisha     Mumbai
2     Mark      Delhi
3    Elena    Chennai
4    Pooja   Banglore
5    Harry  Hyderabad
6     Josh      Surat
7    Kevin     Jaipur
8  Shubham    Kolkata
9     Maya      Akola
 